# Generated by Django 4.2 on 2023-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondLifeBack', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
